import { blendHex } from "../lib/color";
import { withLazySyntaxStyle } from "./syntax";
import type { AppTheme } from "./types";

const TOKYONIGHT_NIGHT_PALETTE = {
  bg: "#1a1b26",
  bg_dark: "#16161e",
  bg_dark1: "#0c0e14",
  blue: "#7aa2f7",
  blue0: "#3d59a1",
  blue1: "#2ac3de",
  blue2: "#0db9d7",
  blue7: "#394b70",
  comment: "#565f89",
  cyan: "#7dcfff",
  dark3: "#545c7e",
  dark5: "#737aa2",
  fg: "#c0caf5",
  fg_dark: "#a9b1d6",
  fg_gutter: "#3b4261",
  green: "#9ece6a",
  green1: "#73daca",
  green2: "#41a6b5",
  magenta: "#bb9af7",
  orange: "#ff9e64",
  purple: "#9d7cd8",
  red: "#f7768e",
  red1: "#db4b4b",
  teal: "#1abc9c",
  terminal_black: "#414868",
  yellow: "#e0af68",
} as const;

/** Tokyo Night Night, a soft high-contrast dark theme with blue-violet accents. */
export const TOKYONIGHT_NIGHT_THEME: AppTheme = withLazySyntaxStyle(
  {
    id: "tokyonight-night",
    label: "Tokyo Night",
    appearance: "dark",
    background: TOKYONIGHT_NIGHT_PALETTE.bg_dark1,
    panel: TOKYONIGHT_NIGHT_PALETTE.bg_dark,
    panelAlt: TOKYONIGHT_NIGHT_PALETTE.bg,
    border: TOKYONIGHT_NIGHT_PALETTE.blue7,
    accent: TOKYONIGHT_NIGHT_PALETTE.blue,
    accentMuted: blendHex(TOKYONIGHT_NIGHT_PALETTE.blue, TOKYONIGHT_NIGHT_PALETTE.bg_dark, 0.2),
    text: TOKYONIGHT_NIGHT_PALETTE.fg,
    muted: TOKYONIGHT_NIGHT_PALETTE.fg_dark,
    addedBg: blendHex(TOKYONIGHT_NIGHT_PALETTE.green, TOKYONIGHT_NIGHT_PALETTE.bg, 0.15),
    removedBg: blendHex(TOKYONIGHT_NIGHT_PALETTE.red1, TOKYONIGHT_NIGHT_PALETTE.bg, 0.15),
    movedAddedBg: blendHex(TOKYONIGHT_NIGHT_PALETTE.blue1, TOKYONIGHT_NIGHT_PALETTE.bg, 0.18),
    movedRemovedBg: blendHex(TOKYONIGHT_NIGHT_PALETTE.magenta, TOKYONIGHT_NIGHT_PALETTE.bg, 0.18),
    contextBg: TOKYONIGHT_NIGHT_PALETTE.bg,
    addedContentBg: blendHex(TOKYONIGHT_NIGHT_PALETTE.green, TOKYONIGHT_NIGHT_PALETTE.bg, 0.25),
    removedContentBg: blendHex(TOKYONIGHT_NIGHT_PALETTE.red1, TOKYONIGHT_NIGHT_PALETTE.bg, 0.25),
    contextContentBg: TOKYONIGHT_NIGHT_PALETTE.bg,
    addedSignColor: TOKYONIGHT_NIGHT_PALETTE.green,
    removedSignColor: TOKYONIGHT_NIGHT_PALETTE.red,
    lineNumberBg: TOKYONIGHT_NIGHT_PALETTE.bg_dark,
    lineNumberFg: TOKYONIGHT_NIGHT_PALETTE.fg_gutter,
    selectedHunk: blendHex(TOKYONIGHT_NIGHT_PALETTE.blue0, TOKYONIGHT_NIGHT_PALETTE.bg, 0.25),
    badgeAdded: TOKYONIGHT_NIGHT_PALETTE.green,
    badgeRemoved: TOKYONIGHT_NIGHT_PALETTE.red,
    badgeNeutral: TOKYONIGHT_NIGHT_PALETTE.fg_dark,
    fileNew: TOKYONIGHT_NIGHT_PALETTE.green,
    fileDeleted: TOKYONIGHT_NIGHT_PALETTE.red,
    fileRenamed: TOKYONIGHT_NIGHT_PALETTE.yellow,
    fileModified: TOKYONIGHT_NIGHT_PALETTE.blue,
    fileUntracked: TOKYONIGHT_NIGHT_PALETTE.cyan,
    noteBorder: TOKYONIGHT_NIGHT_PALETTE.magenta,
    noteBackground: blendHex(TOKYONIGHT_NIGHT_PALETTE.magenta, TOKYONIGHT_NIGHT_PALETTE.bg_dark, 0.12),
    noteTitleBackground: blendHex(TOKYONIGHT_NIGHT_PALETTE.magenta, TOKYONIGHT_NIGHT_PALETTE.bg_dark, 0.22),
    noteTitleText: TOKYONIGHT_NIGHT_PALETTE.fg,
  },
  {
    default: TOKYONIGHT_NIGHT_PALETTE.fg,
    keyword: TOKYONIGHT_NIGHT_PALETTE.magenta,
    string: TOKYONIGHT_NIGHT_PALETTE.green,
    comment: TOKYONIGHT_NIGHT_PALETTE.comment,
    number: TOKYONIGHT_NIGHT_PALETTE.orange,
    function: TOKYONIGHT_NIGHT_PALETTE.blue,
    property: TOKYONIGHT_NIGHT_PALETTE.cyan,
    type: TOKYONIGHT_NIGHT_PALETTE.yellow,
    punctuation: TOKYONIGHT_NIGHT_PALETTE.dark3,
  },
);
